#!/usr/bin/env php
<?php

use Illuminate\Contracts\Console\Kernel;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$status = $kernel->handle($input = new ArgvInput);

// After running the command, we will fire the shutdown event. This allows final
// work to be done by any listeners, as well this will help us flush out any files
// or log information to the proper end locations to be observed.
$kernel->terminate($input, $status);

exit($status);
